export const allSongs = [
  {
    title: "Jerusalem",
    artist: "Master KG",
    like: 120,
    dislike: 3,
    id: 1,
    style: "gospel",
    price: 500,
    lyrics: [
      [
        "Jerusalema ikhaya lami",
        "Ngilondoloze",
        "Uhambe nami",
        "Zungangishiyi lana",
        "Jerusalema ikhaya lami",
      ],
      [
        "Ngilondoloze",
        "Uhambe nami",
        "Zungangishiyi lana",
        "Ndawo yami ayikho lana",
        "Mbuso wami awukho lana",
      ],
      [
        "Ngilondoloze",
        "Zuhambe nami",
        "Ndawo yami ayikho lana",
        "Mbuso wami awukho lana",
      ],
      ["Ngilondoloze", "Zuhambe nami"],
      ["Ngilondoloze ngilondoloze ngilondoloze", "Zungangishiyi lana"],
      ["Ngilondoloze ngilondoloze ngilondoloze", "Zungangishiyi lana"],
      [
        "Ndawo yami ayikho lana",
        "Mbuso wami awukho lana",
        "Ngilondoloze",
        "Zuhambe nami",
      ],
      [" Ngilondoloze ngilondoloze ngilondoloze", "Zungangishiyi lana"],
      ["Ngilondoloze ngilondoloze ngilondoloze", "Zungangishiyi lana"],
    ],
  },
  {
    title: "Just give me a reason",
    artist: "Pink",
    id: 2,
    style: "solo",
    like: 400,
    dislike: 5,
    price: 1000,
    lyrics: [
      [
        "Right from the start",
        "You were a thief, you stole my heart",
        "And I, your willing victim",
        "I let you see the parts of me, that weren't all that pretty",
        "And with every touch you fixed them",
        "Now you've been talking in your sleep oh oh",
        "Things you never say to me oh oh",
        "Tell me that you've had enough",
        "Of our love, our love",
      ],

      [
        "Just give me a reason, just a little bit's enough",
        "Just a second we're not broken just bent, and we can learn to love again",
        "It's in the stars, it's been written in the scars on our hearts",
        "We're not broken just bent, and we can learn to love again",
      ],
      [
        "I'm sorry I don't understand",
        "Where all of this is coming from",
        "I thought that we were fine (oh we had everything)",
        "Your head is running wild again",
        "My dear we still have everythin'",
        "And it's all in your mind (yeah but this is happenin')",
        "You've been havin' real bad dreams oh oh",
        "You used to lie so close to me oh oh",
        "There's nothing more than empty sheets between our love, our love",
        "Oh our love, our love",
      ],
      [
        "Just give me a reason, just a little bit's enough",
        "Just a second we're not broken just bent and we can learn to love again",
        "I never stop, you're still written in the scars on my heart",
        "You're not broken just bent and we can learn to love again",
      ],
      [
        "Oh tear ducts and rust",
        "I'll fix it for us",
        "We are collecting dust, but our love is enough",
        "You are holding it in",
        "You are pouring a drink",
        "No nothing is as bad as it seems",
        "We will come clean",
      ][
        ("Just give me a reason just a little bit's enough",
        "Just a second we're not broken just bent and we can learn to love again",
        "It's in the stars, it's been written in the scars on our hearts",
        "That we're not broken just bent and we can learn to love again")
      ],
      [
        "Just give me a reason, just a little bit's enough",
        "Just a second we're not broken just bent, and we can learn to love again",
        "It's in the stars, it's been written in the scars on our hearts",
        "That we're not broken just bent, and we can learn to love again",
      ],
      [
        "Oh we can learn to love again",
        "Oh we can learn to love again",
        "Oh that we're not broken just bent and we can learn to love again",
      ],
    ],
  },
];
